baseURL = 'https://LiaoPan.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-learn'
publishDir = 'docs'

[params.giscus]
    data_repo="LiaoPan/LiaoPan.github.io"
    data-repo-id="MDEwOlJlcG9zaXRvcnkxMzExMTkyMzc="
    data-category="General"
    data-category-id="DIC_kwDOB9C4hc4CTbqq"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="top"
    data-theme="preferred_color_scheme"
    data-lang="zh-CN"
    data-loading="lazy"
    crossorigin="anonymous"
